### ISSUE TITLE
Domain blocked on Airtel ISP

### ISSUE THREAD

**Issue by alou-S** [Albonycal/stats#1]
albony.xyz domain seems to be blocked on the Airtel ISP.

Tested in three separate locations : Chennai, Bangalore, Hyderabad

```
❯ curl https://mirror.albony.xyz
curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to mirror.albony.xyz:443 

❯ curl http://mirror.albony.xyz
<meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0"/><style>body{margin:0px;padding:0px;}iframe{width:100%;height:100%}</style><iframe src="http://www.airtel.in/court-orders/ " width="100%" height="100%" frameborder=0></iframe>
```

```
sudo pacman -Sy
:: Synchronising package databases...
 core.db failed to download
 extra.db failed to download
 community.db failed to download
 multilib.db failed to download
 chaotic-aur.db failed to download
error: failed retrieving file 'multilib.db' from mirror.albony.xyz : OpenSSL SSL_connect: Connection reset by peer in connection to mirror.albony.xyz:443 
error: failed retrieving file 'chaotic-aur.db' from mirror.albony.xyz : OpenSSL SSL_connect: Connection reset by peer in connection to mirror.albony.xyz:443 
error: failed retrieving file 'core.db' from mirror.albony.xyz : OpenSSL SSL_connect: Connection reset by peer in connection to mirror.albony.xyz:443 
warning: too many errors from mirror.albony.xyz, skipping for the remainder of this transaction
error: failed retrieving file 'extra.db' from mirror.albony.xyz : OpenSSL SSL_connect: Connection reset by peer in connection to mirror.albony.xyz:443 
error: failed retrieving file 'community.db' from mirror.albony.xyz : OpenSSL SSL_connect: Connection reset by peer in connection to mirror.albony.xyz:443 
error: failed to synchronize all databases (download library error)

```

**Comment by alou-S** [comment]
No other ISPs currently seem to block it
Tested ISPs:
ACT Fibernet
Power Grid Corp
Jio Telecom
Tata

**Comment by Albonycal** [comment]
Thank you for bringing this to my attention. This is outrageous, there is no court order to block my services. I literally host them for no profit, it is a volunteer project to make FOSS more accessible to people. I'm contacting airtel to sort this out. 
![image](https://user-images.githubusercontent.com/67057319/208975603-c127e9e5-9cab-4fe5-8dcc-f45cb5232ab4.png)

**Comment by Albonycal** [comment]
My mirror uses Cloudflare CDN and I have tried changing some SSL settings but none work. Airtel uses deep packet inspect (DPI) to block websites. And looks like pacman doesn't use TLS 1.3. 
I'm trying everything to fix this problem :+1:

**Comment by Albonycal** [comment]
I'll try to get another domain. 
Those who want to, You can support this project at: https://www.buymeacoffee.com/albony
by providing donations. 
Thanks

**Comment by Albonycal** [comment]
I got a reply back from Airtel, Lets see what happens: 
![image](https://user-images.githubusercontent.com/67057319/208986242-db7edb66-641c-4dd8-ad72-d3229cf627fd.png)

**Comment by Albonycal** [comment]
A guy from airtel contacted regarding the service request. He had no clue, seem to think that this was a problem with my internet connection. I told him that this is happening all over India. He said "mai dekta hu" (I'll see) 
His tone wasn't convincing.

**Comment by Albonycal** [comment]
I have contacted https://theregister.com/ to write about this problem.

**Comment by Albonycal** [comment]
Got another call from airtel. They seem to think it's a problem with *my* internet connection. They changed the WiFi channel :rofl:

**Comment by alou-S** [comment]
>  And looks like pacman doesn't use TLS 1.3.

Actually its quiet the opposite. Pacman probably does use tls 1.3   
A little testing with curl showed that using the flag `--tlsv1.3`  causes a `OpenSSL SSL_connect: Connection reset by peer` error.   
But using the flags `--tlsv1.2` or 1.1 doesn't seem to have any issue.    
But again v1.0 seems to cause the issue so :clown_face:

**Comment by Albonycal** [comment]
Yea apparently using TLS 1.3 doesn't fully prevent the SNI based blocking. There's a new thing coming called TLS ECH that will fix this. But it's not here yet.

**Comment by Albonycal** [comment]
Finally, after talking with airtel this issue is resolved. My domain is unblocked. When I asked why it was banned, they had no idea. Maybe it's an automated system.
Anyway, thank you for supporting me through this.
