### ISSUE TITLE
Broken pipe failures

### ISSUE THREAD

**Issue by captn3m0** [Albonycal/stats#2]
I'm seeing lots of connection resets and broken pipe errors:

```
python-icalendar-5.0.4-1-any.pkg.tar.zst failed to download
error: failed retrieving file 'python-icalendar-5.0.4-1-any.pkg.tar.zst' from mirror.albony.xyz : Send failure: Broken pipe
```

This is from an ACT connection in Bangalore

**Comment by Albonycal** [comment]
I'll look into this, you shouldn't be getting these.

**Comment by Albonycal** [comment]
Now can you try again and see if those errors come up again?

**Comment by captn3m0** [comment]
Seems to be resolved. Curious to know, what was the issue?

**Comment by Albonycal** [comment]
I was messing with governors and CPU states. But accidentally forced the CPU into a very low power state so that was causing problems when the traffic was high. I need to upgrade to a better server anyway. :sweat_smile:

**Comment by captn3m0** [comment]
Thanks. Not facing any issues, will reopen if I notice anything.
