### ISSUE TITLE
Installing node-red fails because the public key isn't available

### ISSUE THREAD

**Issue by jpelletier** [Albonycal/stats#3]
I got a reply following an issue submitted to node-red. See below:

from your log -

Err:3 http://mirror.albony.xyz/armbian jammy InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 93D6889F9F0E78D5
Reading package lists...
E: Repository 'https://itai-nelken.github.io/weekly-box86-debs/debian  InRelease' changed its 'Origin' value from 'weekly_box86_debs' to ''
E: Repository 'https://itai-nelken.github.io/weekly-box86-debs/debian  InRelease' changed its 'Label' value from 'weekly_box86_debs' to ''
E: Repository 'https://itai-nelken.github.io/weekly-box86-debs/debian  InRelease' changed its 'Codename' value from 'buster' to ''
W: GPG error: https://cli.github.com/packages stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 23F3D4EA75716059
E: The repository 'http://cli.github.com/packages stable InRelease' is not signed.
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://mirror.albony.xyz/armbian jammy InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 93D6889F9F0E78D5
Error executing command, exiting

So it seems that the Armbian repository it is trying to use for nodes isn't fully "signed" so nodejs is failing to install correctly (so then the script fails and then install node 12 from the default repo which doesn't contain npm and etc etc... not good.

**Comment by Albonycal** [comment]
I have no idea about this, my mirror is all synced up so no problems there.

**Comment by jpelletier** [comment]
If your site is OK, it should have a public key.

I tried to get the public key manually without success.
Here's my command below (run as root):
```
# curl -sL http://mirror.albony.xyz/armbian/pubkey.gpg | apt-key add -
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
gpg: no valid OpenPGP data found.

```

**Comment by Albonycal** [comment]
there's a http://mirror.albony.xyz/armbian/armbian.key

**Comment by Albonycal** [comment]
I do not control the contents of the repo, they are synced from upstream armbian repository

**Comment by jpelletier** [comment]
After getting the public key manually and making `sudo apt update`, I retried installing node-red and succeed. Thanks!
There was another repository with a public key problem, but for this issue, it's solved.

**Comment by Albonycal** [comment]
I'm glad that you figured it out :)
