### ISSUE TITLE
Partial Outage

### ISSUE THREAD

**Issue by Albonycal** [Albonycal/stats#4]
https://mirror.albony.xyz  has a partial outage due to HDD failure. 

Repos affected: EndeavourOS, Manjaro, Blackarch and Fdroid. 

I'm working to replace the HDD as soon as possible. This issue will be tracked and updated here: 

Sorry for the inconvenience caused

**Comment by Albonycal** [comment]
The HDD was still under warranty, so seagate will replace it. 
It will take some time though.

**Comment by alou-S** [comment]
> The HDD was still under warranty, so seagate will replace it. It will take some time though.

Give or take 2 to 4 weeks.

**Comment by Albonycal** [comment]
If anyone wants to support mirror.albony.xyz
- https://mirror.albony.xyz/donate.html

Thanks

**Comment by Albonycal** [comment]
I am currently running a `badblocks` test on the HDD to check for bad sectors

**Comment by Albonycal** [comment]
RMA is booked for the HDD, it will get replaced soon :D

**Comment by Albonycal** [comment]
![image](https://github.com/Albonycal/stats/assets/67057319/73e1dafc-b98d-4f8f-8b1c-d5b49fa37c91)
Got the HDD, will start syncing soon :D
